# Generated by Django 5.0.4 on 2024-05-22 16:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='anonymous', max_length=14, verbose_name='name')),
                ('body', models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='pic')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, verbose_name='likes')),
            ],
            options={
                'db_table': 'commit',
            },
        ),
    ]
